# Generated by Django 4.0 on 2022-01-05 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productstore', '0002_alter_mobiles_phone_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobiles',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
